version : '3.8'
 
services:
  peopleapi:
    build: 
      context: .
      dockerfile: /src/peopleapi/Dockerfile
    image: peopleapi
    ports:
      - 2181:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    networks:
      - dotnetcorepromgrafana

  locationapi:
    build: 
      context: .
      dockerfile: /src/locationapi/Dockerfile
    image: locationapi
    ports:
      - 2182:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    networks:
      - dotnetcorepromgrafana

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafana

  grafana: 
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

networks:
  dotnetcorepromgrafana:
